src/models.py
from . import db

class Photo(db.Model):
    __tablename__ = 'photos'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50), nullable=False)
    description = db.Column(db.String(200), nullable=True)
    image = db.Column(db.String(255), nullable=False)

    def __repr__(self) -> str:
        return f"<photo {self.title} {self.description}>"

src/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from .config import Config

db : SQLAlchemy = SQLAlchemy()
migrate : Migrate = Migrate()

def crear_app() -> Flask:
    app = Flask(__name__)
    app.config.from_object(obj=Config)

    db.init_app(app=app)

    from .routes import photo_bp

    app.register_blueprint(blueprint=photo_bp)

    return app

src/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from typing import List, Tuple, Any, Dict
from . import db
from .models import Photo
from .schemas import PhotoCreateSchema

photo_bp = Blueprint('photo_bp', __name__)

@photo_bp.route("/")
def index() -> str:
    photos: List[Tuple[Any]] = Photo.query.all()

    return render_template('index.html', photos=photos)

@photo_bp.route('/photos/new')
def new_photo_form() -> str:
    return render_template("photo_form.html")

@photo_bp.route('/photos', methods=['POST'])
def create_photo() -> str:
    data: Tuple[Any] = request.form

    try:
        PhotoCreateSchema(title=data['title'],
                            description=data['description'],
                            image=str(data['image']))
    
    except ValueError as e:
        return jsonify({"error": e}), 400

    new_photo: Photo = Photo(title=data['title'].title(), 
                        description=data['description'].title(),
                        image=str(data['image']))
    
    db.session.add(new_photo)
    db.session.commit()

    return render_template('photo_item.html', photo=new_photo )


@photo_bp.route('/photos/<int:photo_id>/edit')
def edit_photo_form(photo_id: int) -> str:
    photo: Photo = Photo.query.get_or_404(photo_id)
    return render_template('photo_form.html', photo=photo)

@photo_bp.route('/photos/<int:photo_id>', methods=['DELETE'])
def delete_photo(photo_id: int) -> str:
    photo: Photo = Photo.query.get_or_404(photo_id)

    db.session.delete(photo)
    db.session.commit()
    
    photos: list[Tuple[Any]] = Photo.query.all()
    
    return redirect(url_for('photo_bp.index', photos=photos))

    

@photo_bp.route("/photos/<int:photo_id>", methods=['GET', 'POST'])
def update_photo(photo_id: int) -> str:
    photo: Photo = Photo.query.get_or_404(photo_id)

    if request.method == 'POST':
        data: Dict[str, str] = request.form

        try:
            photo_data: PhotoCreateSchema = PhotoCreateSchema(title=data['title'],
                                                description=data['description'],
                                                image=str(data['image']))
    
        except ValueError as e:
            return jsonify({"error": e}), 400
        
        photo.title = photo_data.title
        photo.description = photo_data.description
        photo.image = photo_data.image

        db.session.commit()

        return redirect(url_for('photo_bp.update_photo', photo_id=photo.id))

    return render_template('photo_item.html', photo=photo)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portal de Usuarios</title>
    <script src="https://unpkg.com/htmx.org@1.4.1"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css">


    
</head>
<body >
    <style>
        body {
          background-color: #121212;
          color: #ffffff;
        }
      </style>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

src/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Portal de Fotos</h1>
<button class="btn btn-primary" hx-get="{{ url_for('photo_bp.new_photo_form') }}" hx-target="#modal">Administrar</button>

<div id="modal"></div>

<div id="photo-list">
    {% for photo in photos %}
        {% include "photo_item.html" %}
    {% endfor %}
</div>

{% endblock %}

src/templates/photo_form.html
<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">{{ "Editar Usuario" if photo else "Añadir Usuario" }}</h5>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
    <div class="modal-body">
        <form hx-post="{{ url_for('photo_bp.create_photo') if not photo else url_for('photo_bp.update_photo', photo_id=photo.id) }}" hx-target="#photo-list" hx-swap="beforeend">
            <div class="form-group">
                <label for="title">Titulo</label>
                <input type="text" name="title" class="form-control" value="{{ photo.title if photo else '' }}" required>
            </div>
            <div class="form-group">
                <label for="description">Descripcion</label>
                <input type="text" name="description" class="form-control" value="{{ photo.description if photo else '' }}" required>
            </div>
            <div class="form-group">
                <label for="image">Url de la imagen</label>
                <input type="url" name="image" class="form-control" value="{{ photo.image if photo else '' }}">
            </div>
            <button type="submit" class="btn btn-primary">{{ "Actualizar" if photo else "Crear" }}</button>
        </form>
    </div>
</div>

src/templates/photo_item.html
<div id="photo-{{ photo.id }}" class="card my-2" style="display: flex;align-items: center;">
    <div class="card-body" style="align-items: center;">
        <h5 class="card-title">{{ photo.title }}</h5>
        <p class="card-description">{{ photo.description }}</p>
        <img src="{{ photo.image }}" alt="photo" height="200dvh">
        <div style="margin-top: 1%; display:block; align-items: center;">
            <button class="btn btn-warning" hx-get="{{ url_for('photo_bp.edit_photo_form', photo_id=photo.id) }}" hx-target="#modal" >Editar</button>
            <button class="btn btn-danger" hx-delete="{{ url_for('photo_bp.delete_photo', photo_id=photo.id) }}" hx-target="#modal" onclick="window.location.reload();">Borrar</button>
        </div>
    </div>
</div>